# Simple bank list for luke_prior_realtime.py
# Generated from CDR Register

BANKS_FROM_CDR_REGISTER = [
    ("Alex.Bank", "alexbank", "https://public.cdr.alex.com.au/cds-au/v1/banking/products"),
    ("AMP Bank GO", "amp-bank-go", "https://pub.cdr-sme.amp.com.au/cds-au/v1/banking/products"),
    ("MyState Bank", "mystate-bank", "https://public.cdr.mystate.com.au/cds-au/v1/banking/products"),
    ("PayPal Australia", "paypal-australia", "https://api.paypal.com/v1/identity/cds-au/v1/banking/products"),
    ("Wise", "wise", "https://au-cdrbanking-pub.wise.com/cds-au/v1/banking/products"),
    ("ME Bank", "me-bank", "https://public.openbank.mebank.com.au/cds-au/v1/banking/products"),
    ("Thriday", "thriday", "https://public.cdr.thriday.com.au/cds-au/v1/banking/products"),
    ("HSBC Bank Australia Limited – Wholesale Banking", "hsbc-bank-australia-limited-–-wholesale-banking", "https://public.ob.business.hsbc.com.au/cds-au/v1/banking/products"),
    ("Greater Bank Limited", "greater-bank-limited", "https://public.cdr.greater.com.au/cds-au/v1/banking/products"),
    ("Arab Bank Australia Limited", "arab-bank-australia-limited", "https://public.cdr.arabbank.com.au/cds-au/v1/banking/products"),
    ("Northern Inland Credit Union Limited", "northern-inland-credit-union-limited", "https://secure.nicu.com.au/cds-au/v1/banking/products"),
    ("ME Bank - ME Go", "me-bank---me-go", "https://api.cds.mebank.com.au/cds-au/v1/banking/products"),
    ("Great Southern Bank Business+", "great-southern-bank-business+", "https://od1.open-banking.business.greatsouthernbank.com.au/cds-au/v1/banking/products"),
    ("Police Bank", "police-bank", "https://public.cdr.prd.policebank.com.au/cds-au/v1/banking/products"),
    ("Border Bank", "border-bank", "https://public.cdr.prd.borderbank.com.au/cds-au/v1/banking/products"),
    ("Westpac", "westpac", "https://digital-api.westpac.com.au/cds-au/v1/banking/products"),
    ("NATIONAL AUSTRALIA BANK", "national-australia-bank", "https://openbank.api.nab.com.au/cds-au/v1/banking/products"),
    ("ANZ", "anz", "https://api.anz/cds-au/v1/banking/products"),
    ("CommBank", "commbank", "https://api.commbank.com.au/public/cds-au/v1/banking/products"),
    ("Regional Australia Bank", "regional-australia-bank", "https://public-data.cdr.regaustbank.io/cds-au/v1/banking/products"),
    ("ING BANK (Australia) Ltd", "ing-bank-australia-ltd", "https://id.ob.ing.com.au/cds-au/v1/banking/products"),
    ("AMP - My AMP", "amp---my-amp", "https://api.cdr-api.amp.com.au/cds-au/v1/banking/products"),
    ("CommFCU", "commfcu", "https://netbank.communityfirst.com.au/cf-OpenBanking/cds-au/v1/banking/products"),
    ("Rabobank", "rabobank", "https://openbanking.api.rabobank.com.au/public/cds-au/v1/banking/products"),
    ("Heritage Bank. Please do not use, please use People’s Choice.", "heritage-bank-please-do-not-use-please-use-people’", "https://product.api.heritage.com.au/cds-au/v1/banking/products"),
    ("Bankwest", "bankwest", "https://open-api.bankwest.com.au/bwpublic/cds-au/v1/banking/products"),
    ("First Option Bank", "first-option-bank", "https://internetbanking.firstoption.com.au/cds-au/v1/banking/products"),
    ("Beyond Bank Australia", "beyond-bank-australia", "https://public.cdr.api.beyondbank.com.au/cds-au/v1/banking/products"),
    ("Cairns bank", "cairns-bank", "https://openbanking.cairnsbank.com.au/cds-au/v1/banking/products"),
    ("G&C Mutual Bank", "gandc-mutual-bank", "https://ibank.gcmutualbank.com.au/cds-au/v1/banking/products"),
    ("Teachers Mutual Bank", "teachers-mutual-bank", "https://ob.tmbl.com.au/tmbank/cds-au/v1/banking/products"),
    ("Geelong Bank", "geelong-bank", "https://online.geelongbank.com.au/cds-au/v1/banking/products"),
    ("IMB Bank", "imb-bank", "https://openbank.openbanking.imb.com.au/cds-au/v1/banking/products"),
    ("Suncorp Bank", "suncorp-bank", "https://id-ob.suncorpbank.com.au/cds-au/v1/banking/products"),
    ("Southern Cross Credit Union", "southern-cross-credit-union", "https://cdr.sccu.com.au/cds-au/v1/banking/products"),
    ("Bank of Sydney", "bank-of-sydney", "https://openbank.api.banksyd.com.au/cds-au/v1/banking/products"),
    ("Australian Military Bank", "australian-military-bank", "https://public.open.australianmilitarybank.com.au/cds-au/v1/banking/products"),
    ("RSL Money", "rsl-money", "https://public.open.rslmoney.com.au/cds-au/v1/banking/products"),
    ("Bank First", "bank-first", "https://public.cdr.bankfirst.com.au/cds-au/v1/banking/products"),
    ("Up", "up", "https://api.up.com.au/cds-au/v1/banking/products"),
    ("Broken Hill Bank", "broken-hill-bank", "https://public.cdr-api.bhccu.com.au/cds-au/v1/banking/products"),
    ("Bendigo Bank", "bendigo-bank", "https://api.cdr.bendigobank.com.au/cds-au/v1/banking/products"),
    ("Defence Bank", "defence-bank", "https://product.defencebank.com.au/cds-au/v1/banking/products"),
    ("Summerland Bank", "summerland-bank", "https://public.cdr-api.summerland.com.au/cds-au/v1/banking/products"),
    ("Dnister", "dnister", "https://public.cdr-api.dnister.com.au/cds-au/v1/banking/products"),
    ("Queensland Country Bank", "queensland-country-bank", "https://public.cdr-api.queenslandcountry.bank/cds-au/v1/banking/products"),
    ("Central Murray Bank", "central-murray-bank", "https://secure.cmcu.com.au/cds-au/v1/banking/products"),
    ("P&N Bank", "pandn-bank", "https://public.cdr-api.pnbank.com.au/cds-au/v1/banking/products"),
    ("BCU Bank", "bcu-bank", "https://public.cdr-api.bcu.com.au/cds-au/v1/banking/products"),
    ("Credit Union SA", "credit-union-sa", "https://openbanking.api.creditunionsa.com.au/cds-au/v1/banking/products"),
    ("Gateway Bank", "gateway-bank", "https://public.cdr-api.gatewaybank.com.au/cds-au/v1/banking/products"),
    ("Qudos Bank", "qudos-bank", "https://public.cdr.qudosbank.com.au/cds-au/v1/banking/products"),
    ("Fire Service Credit Union", "fire-service-credit-union", "https://public.cdr-api.fscu.com.au/cds-au/v1/banking/products"),
    ("MOVE Bank", "move-bank", "https://openbanking.movebank.com.au/cds-au/v1/banking/products"),
    ("St.George Bank", "stgeorge-bank", "https://digital-api.stgeorge.com.au/cds-au/v1/banking/products"),
    ("BankSA", "banksa", "https://digital-api.banksa.com.au/cds-au/v1/banking/products"),
    ("Bank of Melbourne", "bank-of-melbourne", "https://digital-api.bankofmelbourne.com.au/cds-au/v1/banking/products"),
    ("RAMS Financial Group Pty Ltd", "rams-financial-group-pty-ltd", "https://digital-api.westpac.com.au/rams/cds-au/v1/banking/products"),
    ("Auswide Bank Ltd", "auswide-bank-ltd", "https://api.auswidebank.com.au/cds-au/v1/banking/products"),
    ("UniBank", "unibank", "https://ob.tmbl.com.au/unibank/cds-au/v1/banking/products"),
    ("Firefighters Mutual Bank", "firefighters-mutual-bank", "https://ob.tmbl.com.au/fmbank/cds-au/v1/banking/products"),
    ("Health Professionals Bank", "health-professionals-bank", "https://ob.tmbl.com.au/hpbank/cds-au/v1/banking/products"),
    ("Bank Australia", "bank-australia", "https://public.cdr.bankaust.com.au/cds-au/v1/banking/products"),
    ("HSBC", "hsbc", "https://public.ob.hsbc.com.au/cds-au/v1/banking/products"),
    ("Tyro Payments", "tyro-payments", "https://public.cdr.tyro.com/cds-au/v1/banking/products"),
    ("Judo Bank", "judo-bank", "https://public.open.judo.bank/cds-au/v1/banking/products"),
    ("Macquarie Bank Limited", "macquarie-bank-limited", "https://api.macquariebank.io/cds-au/v1/banking/products"),
    ("Card Services", "card-services", "https://api.openbanking.cardservicesdirect.com.au/cds-au/v1/banking/products"),
    ("Coles Credit Cards", "coles-credit-cards", "https://api.openbanking.secure.coles.com.au/cds-au/v1/banking/products"),
    ("Kogan Money Credit Cards", "kogan-money-credit-cards", "https://api.openbanking.cards.koganmoney.com.au/cds-au/v1/banking/products"),
    ("Qantas Money Credit Cards", "qantas-money-credit-cards", "https://api.openbanking.qantasmoney.com/cds-au/v1/banking/products"),
    ("Aussie Home Loans", "aussie-home-loans", "https://aussie.openportal.com.au/cds-au/v1/banking/products"),
    ("UBank", "ubank", "https://public.cdr-api.86400.com.au/cds-au/v1/banking/products"),
    ("gmcu", "gmcu", "https://secure.gmcu.com.au/cds-au/v1/banking/products"),
    ("Laboratories Credit Union", "laboratories-credit-union", "https://internetbanking.lcu.com.au/cds-au/v1/banking/products"),
    ("Coastline Bank", "coastline-bank", "https://public.cdr-api.coastline.com.au/cds-au/v1/banking/products"),
    ("Unity Bank", "unity-bank", "https://ibanking.unitybank.com.au/cds-au/v1/banking/products"),
    ("The Capricornian", "the-capricornian", "https://public.cdr.onlinebanking.capricornian.com.au/cds-au/v1/banking/products"),
    ("BankVic", "bankvic", "https://ib.bankvic.com.au/cds-au/v1/banking/products"),
    ("SWSbank", "swsbank", "https://online.swsbank.com.au/cds-au/v1/banking/products"),
    ("Citi", "citi", "https://openbanking.api.citi.com.au/cds-au/v1/banking/products"),
    ("Family First", "family-first", "https://public.cdr.familyfirst.com.au/cds-au/v1/banking/products"),
    ("Police Credit Union Ltd", "police-credit-union-ltd", "https://api.policecu.com.au/cds-au/v1/banking/products"),
    ("ORANGE CREDIT UNION LTD", "orange-credit-union-ltd", "https://online.orangecu.com.au/cds-au/v1/banking/products"),
    ("Illawarra Credit Union Limited", "illawarra-credit-union-limited", "https://onlineteller.cu.com.au/cds-au/v1/banking/products"),
    ("The Mac", "the-mac", "https://onlinebanking.themaccu.com.au/cds-au/v1/banking/products"),
    ("Woolworths Team Bank", "woolworths-team-bank", "https://online.woolworthsteambank.com.au/cds-au/v1/banking/products"),
    ("Australian Unity Bank", "australian-unity-bank", "https://open-banking.australianunity.com.au/cds-au/v1/banking/products"),
    ("People's Choice", "peoples-choice", "https://ob-public.peopleschoice.com.au/cds-au/v1/banking/products"),
    ("Easy Street", "easy-street", "https://ebranch.easystreet.com.au/es-OpenBanking/cds-au/v1/banking/products"),
    ("Maitland Mutual Limited", "maitland-mutual-limited", "https://openbanking.themutual.com.au/cds-au/v1/banking/products"),
    ("Great Southern Bank", "great-southern-bank", "https://api.open-banking.greatsouthernbank.com.au/cds-au/v1/banking/products"),
    ("QBANK", "qbank", "https://banking.qbank.com.au/cds-au/v1/banking/products"),
    ("Horizon Bank", "horizon-bank", "https://onlinebanking.horizonbank.com.au/cds-au/v1/banking/products"),
    ("bankWAW", "bankwaw", "https://onlinebanking.wawcu.com.au/cds-au/v1/banking/products"),
    ("Hume Bank", "hume-bank", "https://ibankob.humebank.com.au/cds-au/v1/banking/products"),
    ("Darling Downs Bank", "darling-downs-bank", "https://openbanking.wcu.com.au/cds-au/v1/banking/products"),
    ("CBA - CommBiz", "cba---commbiz", "https://cdr.commbiz.api.commbank.com.au/cbzpublic/cds-au/v1/banking/products"),
    ("Bank of us", "bank-of-us", "https://api.bankofus.com.au/cds-au/v1/banking/products"),
    ("TMCU", "tmcu", "https://banking.transportmutual.com.au/cds-au/v1/banking/products"),
    ("Australian Mutual Bank LTD", "australian-mutual-bank-ltd", "https://internetbanking.australianmutual.bank/cds-au/v1/banking/products"),
    ("Bank of Queensland Limited", "bank-of-queensland-limited", "https://api.cds.boq.com.au/cds-au/v1/banking/products"),
    ("BOQ Specialist", "boq-specialist", "https://api.cds.boqspecialist.com.au/cds-au/v1/banking/products"),
    ("DDH Graham", "ddh-graham", "https://api.cds.ddhgraham.com.au/cds-au/v1/banking/products"),
    ("RACQ Bank", "racq-bank", "https://cdrbank.racq.com.au/cds-au/v1/banking/products"),
    ("Virgin Money", "virgin-money", "https://api.cds.virginmoney.com.au/cds-au/v1/banking/products"),
    ("Bank of China", "bank-of-china", "https://api-gateway.bankofchina.com.au/cds-au/v1/banking/products"),
    ("ANZ Plus", "anz-plus", "https://cdr.apix.anz/cds-au/v1/banking/products"),
    ("Unloan", "unloan", "https://public.api.cdr.unloan.com.au/cds-au/v1/banking/products"),
    ("Reliance Bank", "reliance-bank", "https://ibanking.reliancebank.com.au/rel-openbanking/cds-au/v1/banking/products"),
    ("Central West CUL", "central-west-cul", "https://ib.cwcu.com.au/cds-au/v1/banking/products"),
    ("Heartland", "heartland", "https://api.cdr.heartlandbank.com.au/cds-au/v1/banking/products"),
    ("Newcastle Permanent Building Society", "newcastle-permanent-building-society", "https://openbank.newcastlepermanent.com.au/cds-au/v1/banking/products"),
    ("BNK Bank (Goldfields Money/BCHL)", "bnk-bank-goldfields-money/bchl", "https://public.cdr.bnk.com.au/cds-au/v1/banking/products"),
    ("Tyro Banking", "tyro-banking", "https://od1.cdr.banking.tyro.com/cds-au/v1/banking/products"),
    ("Solo by MYOB", "solo-by-myob", "https://od1.open-banking.myob.greatsouthernbank.com.au/cds-au/v1/banking/products"),
    ("in1bank ltd.", "in1bank-ltd", "https://cdr.in1bank.com.au/cds-au/v1/banking/products"),
    ("Liberty Financial", "liberty-financial", "https://services.liberty.com.au/api/data-holder-public/cds-au/v1/banking/products"),
    ("Adelaide Bank", "adelaide-bank", "https://api.cdr.adelaidebank.com.au/cds-au/v1/banking/products"),
    ("Traditional Credit Union", "traditional-credit-union", "https://prd.tcu.com.au/cds-au/v1/banking/products"),
]
